LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := openssl
LOCAL_CATEGORY_PATH := libs

LOCAL_AUTOTOOLS_VERSION := 1.0.1k
LOCAL_AUTOTOOLS_ARCHIVE := $(LOCAL_MODULE)-$(LOCAL_AUTOTOOLS_VERSION).tar.gz
LOCAL_AUTOTOOLS_SUBDIR := $(LOCAL_MODULE)-$(LOCAL_AUTOTOOLS_VERSION)

LOCAL_AUTOTOOLS_MAKE_BUILD_ARGS := \
	-j1 \
	CC="$(CCACHE) $(TARGET_CC)"
LOCAL_AUTOTOOLS_MAKE_INSTALL_ARGS := \
	install_sw \
	$(LOCAL_AUTOTOOLS_MAKE_BUILD_ARGS)

define LOCAL_AUTOTOOLS_CMD_CONFIGURE
	$(Q) (cd $(PRIVATE_SRC_DIR); TARGETMACH=$(TARGET_CROSS) \
	./Configure \
		linux-generic32 \
		-DL_ENDIAN \
		$(TARGET_GLOBAL_CFLAGS) shared \
		--prefix=$(TARGET_OUT_STAGING)/usr)
endef

include $(BUILD_AUTOTOOLS)

