LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := luajit
LOCAL_DESCRIPTION := a Just-In-Time Compiler for Lua
LOCAL_CATEGORY_PATH := scripting

LOCAL_AUTOTOOLS_VERSION := 2.0.3
LOCAL_AUTOTOOLS_ARCHIVE := LuaJIT-$(LOCAL_AUTOTOOLS_VERSION).tar.gz
LOCAL_AUTOTOOLS_SUBDIR := LuaJIT-$(LOCAL_AUTOTOOLS_VERSION)

define LOCAL_AUTOTOOLS_CMD_CONFIGURE
	$(empty)
endef

LOCAL_AUTOTOOLS_MAKE_INSTALL_ARGS := \
	PREFIX="/usr" \
	DESTDIR="$(TARGET_OUT_STAGING)"

ifneq ("$(TARGET_LIBC)","native")
LOCAL_AUTOTOOLS_MAKE_BUILD_ARGS := \
	CROSS="$(TARGET_CROSS)" \
	HOST_CC="$(HOST_CC) -m32"
else
LOCAL_AUTOTOOLS_MAKE_BUILD_ENV := $(TARGET_AUTOTOOLS_CONFIGURE_ENV)
LOCAL_AUTOTOOLS_MAKE_INSTALL_ENV := $(TARGET_AUTOTOOLS_CONFIGURE_ENV)
endif

include $(BUILD_AUTOTOOLS)
